name: Development CI

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_debug_variant:
    name: Build debug variant
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
      - uses: maierj/fastlane-action@v3.0.0
        with:
          lane: ${{ github.ref == 'refs/heads/main' && 'upload_firebase' || github.ref == 'refs/heads/development' && 'build_debug' || 'build_debug' }}
      - uses: actions/upload-artifact@v3
        with:
          name: android-debug-apk
          path: app/build/outputs/apk/**/**/*.apk